### PR TITLE
Added table of contents using doctoc

### PR DESCRIPTION
**Pull request by vcheriyan**
Added table of contents using doctoc.

None of the actual content was updated.

### CODE REVIEW

**Comment by gcaprio** [comment]
@vcheriyan Can you add some documentation around regenerating these TOCs when necessary ?

**Comment by vcheriyan** [comment]
@gcaprio Let me know where I can add the following documentation:

To regenerate the TOCs, run

''' doctoc .

in the project directory. It recursively scans all .MD files and adds TOC. To install doctoc, type in

'''npm install -g doctoc

doctoc git repo is: https://github.com/thlorenz/doctoc

**Comment by gcaprio** [comment]
You can add it to a new section in the README.md file.

**Comment by vcheriyan** [comment]
Updated PR

**Pull request merged**
